ARG AARCH_BALENA_IMAGE=%%BALENA_MACHINE_NAME%%

FROM balenalib/${AARCH_BALENA_IMAGE}-python

#Install 
COPY ./requirements.sh /requirements.sh
RUN bash requirements.sh

RUN install_packages openssh-server gcc

COPY ./start.sh /usr/src/app/start.sh
COPY ./src /usr/src/app/
WORKDIR /usr/src/app

CMD ["bash", "start.sh"]
